app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin
  baseUrl: https://backstage.private.ironsrc.mobi

backend:
  baseUrl: https://backstage-backend.private.ironsrc.mobi
  listen:
    port: 7007
  database:
    client: "pg"
    connection:
      host: "backstage-postgresql"
      port: "5432"
      user: "backend-user"
      database: "backstage_plugin_catalog"
auth:
  environment: production
  providers:
    github:
      production:
        clientId: 4e689be8bfa22726b4fe
        clientSecret: 10f2cff0752874527da705099e5a57a65b36664b
integrations:
  github:
    - host: github.com
      apps:
        - $include: github-app.yaml
